INCLUDEPATH += ..

SOURCES += \
    ../core/variant.cpp \
    ../core/parser.cpp \
    ../core/objecttypetemplate.cpp \
    ../core/objecttype.cpp \
    ../core/object.cpp \
    ../core/moduleloader.cpp \
    ../core/module.cpp \
    ../core/containerparser.cpp \
    ../core/file/esfragmentedfile.cpp \
    ../core/file/file.cpp \
    ../core/file/psifragmentedfile.cpp \
    ../core/file/fragmentedfile.cpp \
    ../core/file/realfile.cpp \
    ../core/formatdetector/syncbyteformatdetector.cpp \
    ../core/formatdetector/standardformatdetector.cpp \
    ../core/formatdetector/magicformatdetector.cpp \
    ../core/formatdetector/formatdetector.cpp \
    ../core/formatdetector/extensionformatdetector.cpp \
    ../core/formatdetector/compositeformatdetector.cpp \
    ../core/interpreter/program.cpp \
    ../core/interpreter/programloader.cpp \
    ../core/interpreter/fromfileparser.cpp \
    ../core/interpreter/fromfilemodule.cpp \
    ../core/interpreter/filter.cpp \
    ../core/interpreter/evaluator.cpp \
    ../core/interpreter/blockexecution.cpp \
    ../core/log/logger.cpp \
    ../core/log/logmanager.cpp \
    ../core/log/streamlogger.cpp \
    ../core/modules/default/elementarycontainerparser.cpp \
    ../core/modules/default/tupleparser.cpp \
    ../core/modules/default/fileparser.cpp \
    ../core/modules/default/defaultmodule.cpp \
    ../core/modules/default/arrayparser.cpp \
    ../core/modules/default/dataparser.cpp \
    ../core/modules/default/structparser.cpp \
    ../core/modules/default/wordparser.cpp \
    ../core/modules/default/intparser.cpp \
    ../core/modules/default/floatparser.cpp \
    ../core/modules/default/bitparser.cpp \
    ../core/modules/default/enumparser.cpp \
    ../core/modules/ebml/ebmlsimpleparser.cpp \
    ../core/modules/ebml/ebmlmodule.cpp \
    ../core/modules/ebml/ebmlmasterparser.cpp \
    ../core/modules/ebml/ebmllargeintegerparser.cpp \
    ../core/modules/ebml/ebmldateparser.cpp \
    ../core/modules/ebml/ebmlcontainerparser.cpp \
    ../core/modules/hmc/hmcmodule.cpp \
    ../core/modules/mkv/mkvmodule.cpp \
    ../core/modules/stream/streammodule.cpp \
    ../core/modules/stream/parentpidparser.cpp \
    ../core/util/strutil.cpp \
    ../core/util/iterutil.cpp \
    ../core/util/fileutil.cpp \
    ../core/util/csvreader.cpp \
    ../core/util/bitutil.cpp \
    ../core/util/osutil.cpp \
    ../core/variable/variable.cpp \
    ../core/variable/variablecollector.cpp \
    ../core/variable/commonvariable.cpp \
    ../core/variable/localscope.cpp \
    ../core/variable/objectcontext.cpp \
    ../core/variable/objectattributes.cpp \
    ../core/variable/functionscope.cpp \
    ../core/variable/parserscope.cpp \
    ../core/variable/typescope.cpp \
    ../core/variable/objectscope.cpp \
    ../core/variable/arrayscope.cpp \
    ../core/variable/mapscope.cpp \
    ../core/variable/variablepath.cpp \
    ../core/modulesetup.cpp \
    ../core/parsingexception.cpp \
    ../core/modules/default/integertypetemplate.cpp
    

HEADERS  += \ 
    ../core/variant.h\
    ../core/parser.h \
    ../core/objecttypetemplate.h \
    ../core/objecttype.h \
    ../core/object.h \
    ../core/moduleloader.h \
    ../core/module.h \
    ../core/containerparser.h \
    ../core/file/esfragmentedfile.h \
    ../core/file/file.h \
    ../core/file/fragmentedfile.h \
    ../core/file/psifragmentedfile.h \
    ../core/file/realfile.h \
    ../core/formatdetector/syncbyteformatdetector.h \
    ../core/formatdetector/standardformatdetector.h \
    ../core/formatdetector/magicformatdetector.h \
    ../core/formatdetector/formatdetector.h \
    ../core/formatdetector/extensionformatdetector.h \
    ../core/formatdetector/compositeformatdetector.h \
    ../core/interpreter/program.h \
    ../core/interpreter/programloader.h \
    ../core/interpreter/fromfileparser.h \
    ../core/interpreter/fromfilemodule.h \
    ../core/interpreter/filter.h \
    ../core/interpreter/evaluator.h \
    ../core/interpreter/blockexecution.h \
    ../core/log/logger.h \
    ../core/log/logmanager.h \
    ../core/log/streamlogger.h \
    ../core/modules/default/elementarycontainerparser.h \
    ../core/modules/default/dataparser.h \
    ../core/modules/default/tupleparser.h \
    ../core/modules/default/fileparser.h \
    ../core/modules/default/defaultmodule.h \
    ../core/modules/default/arrayparser.h \
    ../core/modules/default/structparser.h \
    ../core/modules/default/wordparser.h \
    ../core/modules/default/intparser.h \
    ../core/modules/default/floatparser.h \
    ../core/modules/default/bitparser.h \
    ../core/modules/default/enumparser.h \
    ../core/modules/ebml/ebmlsimpleparser.h \
    ../core/modules/ebml/ebmlmodule.h \
    ../core/modules/ebml/ebmlmasterparser.h \
    ../core/modules/ebml/ebmllargeintegerparser.h \
    ../core/modules/ebml/ebmldateparser.h \
    ../core/modules/ebml/ebmlcontainerparser.h \
    ../core/modules/hmc/hmcmodule.h \
    ../core/modules/mkv/mkvmodule.h \
    ../core/modules/stream/streammodule.h \
    ../core/modules/stream/parentpidparser.h \
    ../core/util/unused.h \
    ../core/util/strutil.h \
    ../core/util/iterutil.h \
    ../core/util/fileutil.h \
    ../core/util/csvreader.h \
    ../core/util/bitutil.h \
    ../core/util/ptrutil.h \
    ../core/util/osutil.h \
    ../core/util/rapidxml/rapidxml_utils.hpp \
    ../core/util/rapidxml/rapidxml_print.hpp \
    ../core/util/rapidxml/rapidxml_iterators.hpp \
    ../core/util/rapidxml/rapidxml.hpp \
    ../compiler/model.h \
    ../core/variable/variable.h \
    ../core/variable/variablepath.h \
    ../core/variable/variablecollector.h \
    ../core/variable/commonvariable.h \
    ../core/variable/localscope.h \
    ../core/variable/objectcontext.h \
    ../core/variable/objectattributes.h \
    ../core/variable/functionscope.h \
    ../core/variable/typescope.h \
    ../core/variable/objectscope.h \
    ../core/variable/arrayscope.h \
    ../core/variable/mapscope.h \
    ../core/variable/parserscope.h \
    ../core/varianthash.h \
    ../core/modulesetup.h \
    ../core/parsingexception.h \
    ../core/modules/default/integertypetemplate.h


